### ISSUE TITLE
An Error!

### ISSUE THREAD

**Issue by YyItRoad** [aarongarvey/binance#1]
when i run the demo follow the README
`node_modules/binance/lib/rest.js:8
class BinanceRest {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)`

**Comment by aarongarvey** [comment]
Which version of node are you using?
