### ISSUE TITLE
new crash

### ISSUE THREAD

**Issue by joaosauer** [aarongarvey/binance#26]
Hi,

I made a search here and didn't find this crash before.  Also, I'm using the version 1.3.0, that I believe is the last one.
```
Users/gekko/node_modules/binance/lib/rest.js:78
                    if (response.statusCode === 400 && payload.code === -1021 &&
                                ^

TypeError: Cannot read property 'statusCode' of undefined
    at Request.request [as _callback] (/Users/gekko/node_modules/binance/lib/rest.js:78:33)
    at self.callback (/Users/gekko/node_modules/request/request.js:186:22)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Timeout._onTimeout (/Usersgekko/node_modules/request/request.js:849:16)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```

**Comment by aarongarvey** [comment]
I accidentally introduced an error into the error handling with the latest code.  Should be fixed now in 1.3.1
