### ISSUE TITLE
error from RVS

### ISSUE THREAD

**Issue by jjhesk** [aarongarvey/binance#36]
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: RSV2 and RSV3 must be clear
    at Receiver.getInfo (/Users/xxx/Documents/czJxARI/node_modules/binance/node_modules/ws/lib/Receiver.js:184:18)
    at Receiver.startLoop (/Users/xxx/Documents/czJxARI/node_modules/binance/node_modules/ws/lib/Receiver.js:153:16)
    at Receiver.add (/Users/xxx/Documents/czJxARI/node_modules/binance/node_modules/ws/lib/Receiver.js:139:10)
    at TLSSocket._ultron.on (/Users/xxx/Documents/czJxARI/node_modules/binance/node_modules/ws/lib/WebSocket.js:138:22)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:594:20)
```

got error from the console.

**Comment by aarongarvey** [comment]
Only having a stack trace is not really much to go on.  Context?  The surrounding code?  What were the circumstances around the error?  Do you have any idea how to reproduce it?

Next, although the error is coming from my library, there's not actually any of my code in the stack trace.  It's in the binance module, but it's all in the dependent websocket library.  Once you've given me some more information, perhaps I can decide whether this error can be caught and appropriately handled.

**Comment by jjhesk** [comment]
its ok, let me make a PR. i know how to fix this

**Comment by jjhesk** [comment]
it is coming from the connection issue error RVS2 RVS3 issue. it can be covered by the error event. Sometimes the system got the errors from json parsing as well. it is the best to cover that on parsing the json error to avoid crash on the client server. thanks
