### ISSUE TITLE
Error: Unexpected server response: 504

### ISSUE THREAD

**Issue by jdevelvis** [aarongarvey/binance#52]
Hello! I'm trying to set up websockets to monitor order books (depth = 10) and this error keeps killing my code:

> Error: Unexpected server response: 504
>     at ClientRequest.req.on (/Users/me/Desktop/code/binance/node_modules/ws/lib/websocket.js:590:5)
>     at emitOne (events.js:116:13)
>     at ClientRequest.emit (events.js:211:7)
>     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
>     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
>     at TLSSocket.socketOnData (_http_client.js:440:20)
>     at emitOne (events.js:116:13)
>     at TLSSocket.emit (events.js:211:7)
>     at addChunk (_stream_readable.js:263:12)
>     at readableAddChunk (_stream_readable.js:250:11)

Occasionally it's 502, as well.

Is there a way to catch the error in my code? I don't see an onError event or anything. I tried putting the .onDepthLevelUpdate function in a try/catch block, to no avail.

Thanks!
Jason

Editing to add some additional detail: It's intermittent (as expected from 502/504 errors) but typically happens ~20-30 seconds after I start the sockets.

**Comment by jdevelvis** [comment]
Update: Since the actual websockets object gets returned, I just added .on('error'... and .on('close' to it, and it caught the errors (mostly) elegantly! At least it stops the process from dying, and I can set it to restart the WS when it catches the close.

I'll mark this closed, thanks for letting me talk through it, haha! 👍
